/**
 * Cerfa code → screener column name mapping.
 * Generated from a 2000-row sample of liasse_postes.
 * Column names are LOWERCASE (Postgres folds unquoted identifiers to lowercase).
 */

export type CerfaCodeMeta = {
  code: string;
  column: string;
  libelle: string;
  pages: number[];
  colonnes: string[];
  occurrences_in_sample: number;
};

export const CERFA_CODE_MAP: Record<string, CerfaCodeMeta> = {
  "EE": { code: "EE", column: "c_ee", libelle: "TOTAL GENERAL (I à V)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1539 },
  "CO": { code: "CO", column: "c_co", libelle: "TOTAL GENERAL (0 à V)", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 1539 },
  "DL": { code: "DL", column: "c_dl", libelle: "TOTAL (I)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1538 },
  "CJ": { code: "CJ", column: "c_cj", libelle: "TOTAL (II)", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 1535 },
  "DA": { code: "DA", column: "c_da", libelle: "Capital social ou individuel", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1530 },
  "DI": { code: "DI", column: "c_di", libelle: "RESULTAT DE L’EXERCICE (bénéfice ou perte)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1520 },
  "EC": { code: "EC", column: "c_ec", libelle: "TOTAL (IV)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1516 },
  "CF": { code: "CF", column: "c_cf", libelle: "Disponibilités", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 1507 },
  "BJ": { code: "BJ", column: "c_bj", libelle: "TOTAL (I)", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 1362 },
  "BZ": { code: "BZ", column: "c_bz", libelle: "Autres créances", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 1338 },
  "DX": { code: "DX", column: "c_dx", libelle: "Dettes fournisseurs et comptes rattachés", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1260 },
  "DY": { code: "DY", column: "c_dy", libelle: "Dettes fiscales et sociales", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1250 },
  "DV": { code: "DV", column: "c_dv", libelle: "Emprunts et dettes financières divers (4)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1178 },
  "GF": { code: "GF", column: "c_gf", libelle: "Total des charges d’exploitation (II)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 1104 },
  "GW": { code: "GW", column: "c_gw", libelle: "RESULTAT COURANT AVANT IMPOTS (I - II + III - IV + V - VI)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 1103 },
  "GG": { code: "GG", column: "c_gg", libelle: "RESULTAT D’EXPLOITATION (I - II)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 1102 },
  "HM": { code: "HM", column: "c_hm", libelle: "TOTAL DES CHARGES (II + IV + VI + VIII + IX + X)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1099 },
  "AT": { code: "AT", column: "c_at", libelle: "Autres immobilisations corporelles", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 1098 },
  "HN": { code: "HN", column: "c_hn", libelle: "BENEFICE OU PERTE (Total des produits - Total des charges)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1098 },
  "FW": { code: "FW", column: "c_fw", libelle: "Autres achats et charges externes", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 1091 },
  "BX": { code: "BX", column: "c_bx", libelle: "Clients et comptes rattachés", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 1058 },
  "DD": { code: "DD", column: "c_dd", libelle: "Réserve légale (1)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 1045 },
  "HL": { code: "HL", column: "c_hl", libelle: "TOTAL DES PRODUITS (I + III + V + VII)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 989 },
  "EA": { code: "EA", column: "c_ea", libelle: "Autres dettes", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 906 },
  "VY": { code: "VY", column: "c_vy", libelle: "TOTAL – ETAT DES DETTES", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 903 },
  "FR": { code: "FR", column: "c_fr", libelle: "Total des produits d’exploitation (I)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 886 },
  "CH": { code: "CH", column: "c_ch", libelle: "Charges constatées d’avance", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 877 },
  "VT": { code: "VT", column: "c_vt", libelle: "TOTAL – ETAT DES CREANCES", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 876 },
  "EG": { code: "EG", column: "c_eg", libelle: "Dettes et produits constatés d’avance à moins d’un an", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 873 },
  "DU": { code: "DU", column: "c_du", libelle: "Emprunts et dettes auprès des établissements de crédit (3)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 867 },
  "8B": { code: "8B", column: "c_8b", libelle: "Fournisseurs et comptes rattachés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 858 },
  "FJ": { code: "FJ", column: "c_fj", libelle: "Chiffres d’affaires nets", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 854 },
  "GV": { code: "GV", column: "c_gv", libelle: "RESULTAT FINANCIER (V - VI)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 824 },
  "FX": { code: "FX", column: "c_fx", libelle: "Impôts, taxes et versements assimilés", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 810 },
  "0G": { code: "0G", column: "c_0g", libelle: "ACQUISITIONS Total Général", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 805 },
  "I4": { code: "I4", column: "c_i4", libelle: "DIMINUTIONS Total Général", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 801 },
  "BH": { code: "BH", column: "c_bh", libelle: "Autres immobilisations financières", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 777 },
  "0N": { code: "0N", column: "c_0n", libelle: "AMORTISSEMENTS Total Général", pages: [6], colonnes: ["m3/m4"], occurrences_in_sample: 770 },
  "QU": { code: "QU", column: "c_qu", libelle: "AMORTISSEMENTS Total Immobilisations corporelles", pages: [6], colonnes: ["m3/m4"], occurrences_in_sample: 761 },
  "DG": { code: "DG", column: "c_dg", libelle: "Autres réserves", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 754 },
  "DH": { code: "DH", column: "c_dh", libelle: "Report à nouveau", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 749 },
  "AR": { code: "AR", column: "c_ar", libelle: "Installations techniques, matériel et outillage industriels", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 748 },
  "GE": { code: "GE", column: "c_ge", libelle: "Autres charges", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 734 },
  "GA": { code: "GA", column: "c_ga", libelle: "Dot. d’exploit. - Dotations aux amortissements", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 723 },
  "LN": { code: "LN", column: "c_ln", libelle: "ACQUISITIONS Total Immobilisations corporelles", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 717 },
  "IY": { code: "IY", column: "c_iy", libelle: "DIMINUTIONS Total Immobilisations corporelles", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 714 },
  "LQ": { code: "LQ", column: "c_lq", libelle: "ACQUISITIONS Total Immobilisations financières", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 709 },
  "FQ": { code: "FQ", column: "c_fq", libelle: "Autres produits", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 706 },
  "I3": { code: "I3", column: "c_i3", libelle: "DIMINUTIONS Total Immobilisations financières", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 705 },
  "FG": { code: "FG", column: "c_fg", libelle: "Production vendue services", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 700 },
  "GU": { code: "GU", column: "c_gu", libelle: "Total des charges financières (VI)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 695 },
  "UX": { code: "UX", column: "c_ux", libelle: "Autres créances clients", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 671 },
  "GP": { code: "GP", column: "c_gp", libelle: "Total des produits financiers (V)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 669 },
  "HK": { code: "HK", column: "c_hk", libelle: "Impôts sur les bénéfices (X)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 665 },
  "VS": { code: "VS", column: "c_vs", libelle: "Charges constatées d’avance", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 662 },
  "FZ": { code: "FZ", column: "c_fz", libelle: "Charges sociales", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 661 },
  "FY": { code: "FY", column: "c_fy", libelle: "Salaires et traitements", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 661 },
  "HI": { code: "HI", column: "c_hi", libelle: "RESULTAT EXCEPTIONNEL (VII - VIII)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 651 },
  "8D": { code: "8D", column: "c_8d", libelle: "Sécurité sociale et autres organismes sociaux", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 650 },
  "GR": { code: "GR", column: "c_gr", libelle: "Intérêts et charges assimilées", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 635 },
  "8K": { code: "8K", column: "c_8k", libelle: "Autres dettes (dont dettes relatives à des opérations de pension de titre)", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 610 },
  "HH": { code: "HH", column: "c_hh", libelle: "Total des charges exceptionnelles (VIII)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 606 },
  "AF": { code: "AF", column: "c_af", libelle: "Concessions, brevets et droits similaires", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 598 },
  "VB": { code: "VB", column: "c_vb", libelle: "T. V. A.", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 594 },
  "VQ": { code: "VQ", column: "c_vq", libelle: "Autres impôts, taxes et assimilés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 589 },
  "VI": { code: "VI", column: "c_vi", libelle: "Groupe et associés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 577 },
  "VR": { code: "VR", column: "c_vr", libelle: "Débiteurs divers (dont créances relatives à des opérations de pension de titres)", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 577 },
  "VW": { code: "VW", column: "c_vw", libelle: "T.V.A.", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 572 },
  "IO": { code: "IO", column: "c_io", libelle: "DIMINUTIONS Total dont autres postes d’immobilisations incorporelles", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 566 },
  "KD": { code: "KD", column: "c_kd", libelle: "ACQUISITIONS Total dont autres postes d’immobilisations incorporelles", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 566 },
  "UT": { code: "UT", column: "c_ut", libelle: "Autres immobilisations financières", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 563 },
  "PE": { code: "PE", column: "c_pe", libelle: "AMORTISSEMENTS Total dont autres immobilisations incorporelles", pages: [6], colonnes: ["m3/m4"], occurrences_in_sample: 539 },
  "HD": { code: "HD", column: "c_hd", libelle: "Total des produits exceptionnels (VII)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 518 },
  "8C": { code: "8C", column: "c_8c", libelle: "Personnel et comptes rattachés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 517 },
  "FP": { code: "FP", column: "c_fp", libelle: "Reprises sur amortissements et provisions, transfert de charges", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 496 },
  "CU": { code: "CU", column: "c_cu", libelle: "Autres participations", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 479 },
  "GL": { code: "GL", column: "c_gl", libelle: "Autres intérêts et produits assimilés", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 478 },
  "AH": { code: "AH", column: "c_ah", libelle: "Fonds commercial", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 472 },
  "180": { code: "180", column: "c_180", libelle: "Total général Passif", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 457 },
  "HE": { code: "HE", column: "c_he", libelle: "Charges exceptionnelles sur opérations de gestion", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 457 },
  "110": { code: "110", column: "c_110", libelle: "Total général Actif", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 457 },
  "142": { code: "142", column: "c_142", libelle: "Total des capitaux propres - Total I", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 456 },
  "096": { code: "096", column: "c_096", libelle: "Total Actif circulant + Charges constatées d’avance", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 454 },
  "120": { code: "120", column: "c_120", libelle: "Capital social ou individuel", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 454 },
  "7C": { code: "7C", column: "c_7c", libelle: "TOTAL GENERAL", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 449 },
  "136": { code: "136", column: "c_136", libelle: "Résultat de l’exercice", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 448 },
  "084": { code: "084", column: "c_084", libelle: "Disponibilités", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 442 },
  "BT": { code: "BT", column: "c_bt", libelle: "Marchandises", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 427 },
  "176": { code: "176", column: "c_176", libelle: "Total des dettes", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 425 },
  "VH": { code: "VH", column: "c_vh", libelle: "Emprunts à plus d’1 an à l’origine", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 423 },
  "AP": { code: "AP", column: "c_ap", libelle: "Constructions", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 405 },
  "VG": { code: "VG", column: "c_vg", libelle: "Emprunts à 1 an maximum à l’origine", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 401 },
  "VK": { code: "VK", column: "c_vk", libelle: "Emprunts remboursés en cours d’exercice", pages: [8], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 400 },
  "172": { code: "172", column: "c_172", libelle: "Autres dettes", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 400 },
  "FU": { code: "FU", column: "c_fu", libelle: "Achats de matières premières et autres approvisionnements", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 388 },
  "264": { code: "264", column: "c_264", libelle: "Total des charges d’exploitation", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 379 },
  "310": { code: "310", column: "c_310", libelle: "Bénéfice ou perte", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 378 },
  "270": { code: "270", column: "c_270", libelle: "Résultat d’exploitation", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 378 },
  "FS": { code: "FS", column: "c_fs", libelle: "Achats de marchandises (y compris droits de douane)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 373 },
  "242": { code: "242", column: "c_242", libelle: "Autres charges externes*", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 369 },
  "BL": { code: "BL", column: "c_bl", libelle: "Matières premières, approvisionnements", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 362 },
  "7B": { code: "7B", column: "c_7b", libelle: "Total Provisions pour dépréciation", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 362 },
  "FA": { code: "FA", column: "c_fa", libelle: "Ventes de marchandises", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 342 },
  "044": { code: "044", column: "c_044", libelle: "Total Actif Immobilisé", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 337 },
  "HB": { code: "HB", column: "c_hb", libelle: "Produits exceptionnels sur opérations en capital", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 324 },
  "072": { code: "072", column: "c_072", libelle: "Créances – Autres", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 324 },
  "232": { code: "232", column: "c_232", libelle: "Total des produits d’exploitation hors T.V.A.", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 317 },
  "CD": { code: "CD", column: "c_cd", libelle: "Valeurs mobilières de placement", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 311 },
  "HA": { code: "HA", column: "c_ha", libelle: "Produits exceptionnels sur opérations de gestion", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 305 },
  "BV": { code: "BV", column: "c_bv", libelle: "Avances et acomptes versés sur commandes", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 295 },
  "BD": { code: "BD", column: "c_bd", libelle: "Autres titres immobilisés", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 289 },
  "6T": { code: "6T", column: "c_6t", libelle: "Sur comptes clients", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 282 },
  "166": { code: "166", column: "c_166", libelle: "Fournisseurs et comptes rattachés", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 281 },
  "HF": { code: "HF", column: "c_hf", libelle: "Charges exceptionnelles sur opérations en capital", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 277 },
  "EH": { code: "EH", column: "c_eh", libelle: "Dont concours bancaires courants, et soldes créditeurs de banques et C.C.P.", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 276 },
  "DW": { code: "DW", column: "c_dw", libelle: "Avances et acomptes reçus sur commandes en cours", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 273 },
  "UE": { code: "UE", column: "c_ue", libelle: "dont dotations et reprises : - d’Exploitation", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 271 },
  "FT": { code: "FT", column: "c_ft", libelle: "Variation de stock (marchandises)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 267 },
  "GC": { code: "GC", column: "c_gc", libelle: "Dot. d’exploit. Sur actif circulant : dotations aux provisions", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 266 },
  "VA": { code: "VA", column: "c_va", libelle: "Clients douteux ou litigieux", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 263 },
  "VM": { code: "VM", column: "c_vm", libelle: "Impôts sur les bénéfices", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 261 },
  "DR": { code: "DR", column: "c_dr", libelle: "TOTAL (III)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 260 },
  "FO": { code: "FO", column: "c_fo", libelle: "Subventions d’exploitation", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 253 },
  "028": { code: "028", column: "c_028", libelle: "Immobilisations corporelles", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 250 },
  "EI": { code: "EI", column: "c_ei", libelle: "Dont emprunts participatifs", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 242 },
  "218": { code: "218", column: "c_218", libelle: "Production vendue de services - France", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 242 },
  "134": { code: "134", column: "c_134", libelle: "Report à nouveau", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 241 },
  "EB": { code: "EB", column: "c_eb", libelle: "Produits constatés d’avance (2)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 237 },
  "FV": { code: "FV", column: "c_fv", libelle: "Variation de stock (matières premières et approvisionnements)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 236 },
  "UY": { code: "UY", column: "c_uy", libelle: "Personnel et comptes rattachés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 233 },
  "VC": { code: "VC", column: "c_vc", libelle: "Groupe et associés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 226 },
  "244": { code: "244", column: "c_244", libelle: "Impôts, taxes et versements assimilés", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 224 },
  "VJ": { code: "VJ", column: "c_vj", libelle: "Emprunts souscrits en cours d’exercice", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 223 },
  "8A": { code: "8A", column: "c_8a", libelle: "Emprunts et dettes financières divers", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 223 },
  "GJ": { code: "GJ", column: "c_gj", libelle: "Produits financiers de participations", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 221 },
  "FD": { code: "FD", column: "c_fd", libelle: "Production vendue biens", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 218 },
  "5Z": { code: "5Z", column: "c_5z", libelle: "Total Provisions pour risques et charges", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 218 },
  "DP": { code: "DP", column: "c_dp", libelle: "Provisions pour risques", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 216 },
  "AN": { code: "AN", column: "c_an", libelle: "Terrains", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 209 },
  "A1": { code: "A1", column: "c_a1", libelle: "ACTIF - Créances sur les Ets de crédit", pages: [1,4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 208 },
  "8E": { code: "8E", column: "c_8e", libelle: "Impôts sur les bénéfices", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 207 },
  "254": { code: "254", column: "c_254", libelle: "Dotations aux amortissements", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 203 },
  "YP": { code: "YP", column: "c_yp", libelle: "Effectif moyen du personnel", pages: [11,16], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 199 },
  "040": { code: "040", column: "c_040", libelle: "Immobilisations financières", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 199 },
  "CP": { code: "CP", column: "c_cp", libelle: "Parts à moins d’un an", pages: [1], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 197 },
  "DB": { code: "DB", column: "c_db", libelle: "Primes d’émission, de fusion, d’apport, …", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 194 },
  "068": { code: "068", column: "c_068", libelle: "Créances – Clients et comptes rattachés", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 192 },
  "VP": { code: "VP", column: "c_vp", libelle: "Divers", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 185 },
  "306": { code: "306", column: "c_306", libelle: "Impôts sur les bénéfices", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 180 },
  "126": { code: "126", column: "c_126", libelle: "Réserve légale", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 178 },
  "252": { code: "252", column: "c_252", libelle: "Charges sociales", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 178 },
  "169": { code: "169", column: "c_169", libelle: "Autres dettes dont comptes courant d’associés de l’exercice N", pages: [1], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 173 },
  "250": { code: "250", column: "c_250", libelle: "Rémunérations du personnel", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 172 },
  "AJ": { code: "AJ", column: "c_aj", libelle: "Autres immobilisations incorporelles", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 171 },
  "8L": { code: "8L", column: "c_8l", libelle: "Produits constatés d’avance", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 163 },
  "230": { code: "230", column: "c_230", libelle: "Autres produits", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 162 },
  "262": { code: "262", column: "c_262", libelle: "Autres charges", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 155 },
  "UZ": { code: "UZ", column: "c_uz", libelle: "Sécurité Sociale, autres organismes sociaux", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 151 },
  "ZJ": { code: "ZJ", column: "c_zj", libelle: "Total du poste correspondant à la ligne FW du tableau n° 2052", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 150 },
  "AV": { code: "AV", column: "c_av", libelle: "Immobilisations en cours", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 150 },
  "HP": { code: "HP", column: "c_hp", libelle: "Renvois : Crédit-bail mobilier", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 149 },
  "ST": { code: "ST", column: "c_st", libelle: "Autres comptes", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 148 },
  "FM": { code: "FM", column: "c_fm", libelle: "Production stockée", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 147 },
  "294": { code: "294", column: "c_294", libelle: "Charges financières", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 145 },
  "SS": { code: "SS", column: "c_ss", libelle: "Rémunération d’intermédiaires et honoraires (hors rétrocessions)", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 144 },
  "490": { code: "490", column: "c_490", libelle: "Total Immobilisations (Valeur brute)", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 143 },
  "YX": { code: "YX", column: "c_yx", libelle: "Total du compte correspondant à la ligne FX du tableau n° 2052", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 141 },
  "YZ": { code: "YZ", column: "c_yz", libelle: "Total TVA. déductible sur biens et services", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 137 },
  "182": { code: "182", column: "c_182", libelle: "Coût de revient des immobilisations acquises ou créées au cours de l’exercice", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 136 },
  "156": { code: "156", column: "c_156", libelle: "Emprunts et dettes assimilées", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 135 },
  "9Z": { code: "9Z", column: "c_9z", libelle: "Autres impôts, taxes et versements assimilés", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 134 },
  "YY": { code: "YY", column: "c_yy", libelle: "Montant de la TVA. collectée", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 133 },
  "BN": { code: "BN", column: "c_bn", libelle: "En cours de production de biens", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 131 },
  "XQ": { code: "XQ", column: "c_xq", libelle: "Location, charges locatives et de copropriété", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 130 },
  "YW": { code: "YW", column: "c_yw", libelle: "Taxe professionnelle", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 129 },
  "DZ": { code: "DZ", column: "c_dz", libelle: "Dettes sur immobilisations et comptes rattachés", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 126 },
  "378": { code: "378", column: "c_378", libelle: "Montant de la T.V.A. déductible sur biens et services", pages: [2,4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 126 },
  "BB": { code: "BB", column: "c_bb", libelle: "Créances rattachées à des participations", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 125 },
  "GD": { code: "GD", column: "c_gd", libelle: "Dot. d’exploit. Pour risques et charges : dotations aux provisions", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 120 },
  "300": { code: "300", column: "c_300", libelle: "Charges exceptionnelles", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 118 },
  "234": { code: "234", column: "c_234", libelle: "Achats de marchandises (y compris droits de douane)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 111 },
  "HG": { code: "HG", column: "c_hg", libelle: "Dotations exceptionnelles aux amortissements et provisions", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 108 },
  "374": { code: "374", column: "c_374", libelle: "Montant de la T.V.A. collectée", pages: [2,4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 106 },
  "YT": { code: "YT", column: "c_yt", libelle: "Sous-traitance", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 104 },
  "6N": { code: "6N", column: "c_6n", libelle: "Sur stocks et en cours", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 103 },
  "092": { code: "092", column: "c_092", libelle: "Charges constatées d’avance", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 103 },
  "132": { code: "132", column: "c_132", libelle: "Autres réserves", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 102 },
  "CS": { code: "CS", column: "c_cs", libelle: "Participations évaluées - mise en équivalence", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 102 },
  "238": { code: "238", column: "c_238", libelle: "Achats de matières premières et autres approvisionnements (y compris droits de douane)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 100 },
  "A4": { code: "A4", column: "c_a4", libelle: "Renvois : Redevances pour concessions de brevets, de licences (charges)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 99 },
  "HC": { code: "HC", column: "c_hc", libelle: "Reprises sur provisions et transferts de charges", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 98 },
  "243": { code: "243", column: "c_243", libelle: "(dont taxe professionnelle)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 96 },
  "280": { code: "280", column: "c_280", libelle: "Produits financiers", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 96 },
  "BF": { code: "BF", column: "c_bf", libelle: "Prêts", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 94 },
  "DQ": { code: "DQ", column: "c_dq", libelle: "Provisions pour charges", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 93 },
  "492": { code: "492", column: "c_492", libelle: "Total Immobilisations (Augmentations)", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 91 },
  "060": { code: "060", column: "c_060", libelle: "Stock marchandises", pages: [1,7], colonnes: ["m3/m4"], occurrences_in_sample: 91 },
  "5V": { code: "5V", column: "c_5v", libelle: "Autres provisions pour risques et charges", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 89 },
  "GQ": { code: "GQ", column: "c_gq", libelle: "Dotations financières sur amortissements et provisions", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 89 },
  "DK": { code: "DK", column: "c_dk", libelle: "Provisions réglementées", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 88 },
  "UL": { code: "UL", column: "c_ul", libelle: "Créances rattachées à des participations", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 87 },
  "BR": { code: "BR", column: "c_br", libelle: "Produits intermédiaires et finis", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 85 },
  "4A": { code: "4A", column: "c_4a", libelle: "Provisions pour litiges", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 84 },
  "GK": { code: "GK", column: "c_gk", libelle: "Produits des autres valeurs mobilières et créances de l’actif immobilisé", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 84 },
  "UJ": { code: "UJ", column: "c_uj", libelle: "dont dotations et reprises : - Exceptionnelles", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 83 },
  "014": { code: "014", column: "c_014", libelle: "Immobilisations incorporelles – Autres", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 82 },
  "AX": { code: "AX", column: "c_ax", libelle: "Avances et acomptes", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 78 },
  "210": { code: "210", column: "c_210", libelle: "Ventes de marchandises – France", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 78 },
  "8J": { code: "8J", column: "c_8j", libelle: "Dettes sur immobilisations et comptes rattachés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 77 },
  "GN": { code: "GN", column: "c_gn", libelle: "Différences positives de change", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 77 },
  "DJ": { code: "DJ", column: "c_dj", libelle: "Subventions d’investissement", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 74 },
  "GS": { code: "GS", column: "c_gs", libelle: "Différences négatives de change", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 74 },
  "UP": { code: "UP", column: "c_up", libelle: "Prêts", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 69 },
  "3Z": { code: "3Z", column: "c_3z", libelle: "Total Provisions réglementées", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 69 },
  "CR": { code: "CR", column: "c_cr", libelle: "Parts à plus d’un an", pages: [1], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 68 },
  "DE": { code: "DE", column: "c_de", libelle: "Réserves statutaires ou contractuelles", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 65 },
  "HJ": { code: "HJ", column: "c_hj", libelle: "Participation des salariés aux résultats de l’entreprise (IX)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 65 },
  "A2": { code: "A2", column: "c_a2", libelle: "ACTIF - Créances sur la clientèle", pages: [1,4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 61 },
  "195": { code: "195", column: "c_195", libelle: "Dont dettes à plus d’un an", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 59 },
  "UG": { code: "UG", column: "c_ug", libelle: "dont dotations et reprises : - Financières", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 58 },
  "236": { code: "236", column: "c_236", libelle: "Variation de stock (marchandises)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 57 },
  "290": { code: "290", column: "c_290", libelle: "Produits exceptionnels", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 57 },
  "GM": { code: "GM", column: "c_gm", libelle: "Reprises sur provisions et transferts de charges", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 55 },
  "3X": { code: "3X", column: "c_3x", libelle: "Amortissements dérogatoires", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 54 },
  "CY": { code: "CY", column: "c_cy", libelle: "AMORTISSEMENTS Frais d’établissement, et de développement ou de recherche", pages: [6], colonnes: ["m3/m4"], occurrences_in_sample: 54 },
  "BP": { code: "BP", column: "c_bp", libelle: "En cours de production de services", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 54 },
  "FN": { code: "FN", column: "c_fn", libelle: "Production immobilisée", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 54 },
  "I2": { code: "I2", column: "c_i2", libelle: "DIMINUTIONS Prêts et immobilisations financières", pages: [5], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 53 },
  "IN": { code: "IN", column: "c_in", libelle: "DIMINUTIONS Frais d’établissement, et de développement ou de recherche", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 53 },
  "YU": { code: "YU", column: "c_yu", libelle: "Personnel extérieur à l’entreprise", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 52 },
  "CZ": { code: "CZ", column: "c_cz", libelle: "ACQUISITIONS Frais d’établissement, et de développement ou de recherche", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 51 },
  "GO": { code: "GO", column: "c_go", libelle: "Produits nets sur cessions de valeurs mobilières de placement", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 51 },
  "AB": { code: "AB", column: "c_ab", libelle: "Frais d’établissement", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 50 },
  "VN": { code: "VN", column: "c_vn", libelle: "Autres impôts, taxes versements assimilés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 49 },
  "GB": { code: "GB", column: "c_gb", libelle: "Dot. d’exploit. - Dotations aux provisions", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 47 },
  "010": { code: "010", column: "c_010", libelle: "Immobilisations incorporelles - Fonds commercial", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 47 },
  "ZE": { code: "ZE", column: "c_ze", libelle: "Dividendes", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 47 },
  "6X": { code: "6X", column: "c_6x", libelle: "Autres provisions pour dépréciation", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 42 },
  "DF": { code: "DF", column: "c_df", libelle: "Réserves réglementées (1)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 41 },
  "9U": { code: "9U", column: "c_9u", libelle: "sur immobilisations – titres de participation", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 40 },
  "050": { code: "050", column: "c_050", libelle: "Matières premières, approvisionnements, en cours de production", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 39 },
  "080": { code: "080", column: "c_080", libelle: "Valeurs mobilières de placement", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 38 },
  "494": { code: "494", column: "c_494", libelle: "Total Immobilisations (Diminutions)", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 38 },
  "376": { code: "376", column: "c_376", libelle: "Effectif moyen du personnel", pages: [5], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 37 },
  "472": { code: "472", column: "c_472", libelle: "AUGMENTATIONS Imm. corporelles – Autres immobilisations corporelles", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 35 },
  "482": { code: "482", column: "c_482", libelle: "AUGMENTATIONS Immobilisations financières", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 33 },
  "4X": { code: "4X", column: "c_4x", libelle: "Provisions pour pensions et obligations similaires", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 33 },
  "442": { code: "442", column: "c_442", libelle: "AUGMENTATIONS Imm. corporelles – Installations techniques matériel et outillage industriels industriels", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 32 },
  "CX": { code: "CX", column: "c_cx", libelle: "Frais de développement ou de recherche et développement", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 30 },
  "174": { code: "174", column: "c_174", libelle: "Produits constatés d’avance", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 30 },
  "GT": { code: "GT", column: "c_gt", libelle: "Charges nettes sur cessions de valeurs mobilières de placement", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 30 },
  "240": { code: "240", column: "c_240", libelle: "Variation de stock (matières premières et approvisionnement)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 29 },
  "462": { code: "462", column: "c_462", libelle: "AUGMENTATIONS Imm. corporelles – Matériel de transport", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 29 },
  "YQ": { code: "YQ", column: "c_yq", libelle: "Engagement de crédit-bail mobilier", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 28 },
  "EO": { code: "EO", column: "c_eo", libelle: "Provisions pour gros entretien et grandes révisions ou grosses réparations", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 27 },
  "199": { code: "199", column: "c_199", libelle: "Dont comptes courant d’associés débiteurs", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 27 },
  "ED": { code: "ED", column: "c_ed", libelle: "(V)", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 26 },
  "064": { code: "064", column: "c_064", libelle: "Avances et acomptes versés sur commandes", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 24 },
  "214": { code: "214", column: "c_214", libelle: "Production vendue de biens – France", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 24 },
  "GH": { code: "GH", column: "c_gh", libelle: "Bénéfice attribué ou perte transférée (III)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 23 },
  "226": { code: "226", column: "c_226", libelle: "Subventions d’exploitation reçues", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 22 },
  "HQ": { code: "HQ", column: "c_hq", libelle: "Renvois : Crédit-bail immobilier", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 20 },
  "GI": { code: "GI", column: "c_gi", libelle: "Perte supportée ou bénéfice transféré (IV)", pages: [3], colonnes: ["m3/m4"], occurrences_in_sample: 20 },
  "CN": { code: "CN", column: "c_cn", libelle: "Ecarts de conversion actif (V)", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 19 },
  "184": { code: "184", column: "c_184", libelle: "Prix de vente hors T.V.A. des immobilisations cédées au cours de l’exercice", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 19 },
  "06": { code: "06", column: "c_06", libelle: "sur immobilisations – autres immobilisations financières", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 19 },
  "4E": { code: "4E", column: "c_4e", libelle: "Provisions pour garanties données aux clients", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 18 },
  "YV": { code: "YV", column: "c_yv", libelle: "Rétrocessions d’honoraires, commissions et courtages", pages: [11], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 18 },
  "A3": { code: "A3", column: "c_a3", libelle: "Renvois : Redevances pour concessions de brevets, de licences (produits)", pages: [1,4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 18 },
  "DC": { code: "DC", column: "c_dc", libelle: "Ecarts de réévaluation", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 17 },
  "164": { code: "164", column: "c_164", libelle: "Avances et acomptes reçus sur commandes en cours", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 17 },
  "596": { code: "596", column: "c_596", libelle: "Total Immobilisations – Amortissement - Plus-values, Moins-values (Court terme)", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 16 },
  "DT": { code: "DT", column: "c_dt", libelle: "Autres emprunts obligataires", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 16 },
  "4T": { code: "4T", column: "c_4t", libelle: "Provisions pour perte de change", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 14 },
  "6A": { code: "6A", column: "c_6a", libelle: "sur immobilisations – incorporelles", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 14 },
  "140": { code: "140", column: "c_140", libelle: "Provisions réglementées", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 14 },
  "6E": { code: "6E", column: "c_6e", libelle: "sur immobilisations – corporelles", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 13 },
  "193": { code: "193", column: "c_193", libelle: "Dont immobilisations financières à moins d’un an", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 13 },
  "582": { code: "582", column: "c_582", libelle: "Total Plus-values, Moins-values (Valeur résiduelle)", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 13 },
  "DO": { code: "DO", column: "c_do", libelle: "TOTAL (II)", pages: [2], colonnes: ["m3/m4"], occurrences_in_sample: 12 },
  "ZR": { code: "ZR", column: "c_zr", libelle: "ZR", pages: [11], colonnes: ["m3/m4"], occurrences_in_sample: 11 },
  "MY": { code: "MY", column: "c_my", libelle: "DIMINUTIONS Virement postes immobilisations corporelles en cours", pages: [5], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 11 },
  "256": { code: "256", column: "c_256", libelle: "Dotations aux provisions", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 11 },
  "209": { code: "209", column: "c_209", libelle: "Ventes de marchandises – Export", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 10 },
  "CB": { code: "CB", column: "c_cb", libelle: "Capital souscrit et appelé, non versé", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 10 },
  "584": { code: "584", column: "c_584", libelle: "Total Plus-values, Moins-values (Prix de cession)", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 10 },
  "452": { code: "452", column: "c_452", libelle: "AUGMENTATIONS Imm. corporelles – Installations générales, agencements divers", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 10 },
  "217": { code: "217", column: "c_217", libelle: "Production vendue de services - Export", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 10 },
  "412": { code: "412", column: "c_412", libelle: "AUGMENTATIONS Immobilisations incorporelles –Autres immobilisations incorporelles", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 10 },
  "DN": { code: "DN", column: "c_dn", libelle: "Avances conditionnées", pages: [2], colonnes: ["m3/m4"], occurrences_in_sample: 9 },
  "24B": { code: "24B", column: "c_24b", libelle: "(dont crédit bail mobilier)*", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 9 },
  "CW": { code: "CW", column: "c_cw", libelle: "Charges à répartir ou frais d’émission d’emprunt", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 9 },
  "24A": { code: "24A", column: "c_24a", libelle: "(dont crédit bail immobilier)*", pages: [2], colonnes: ["m1/m2"], occurrences_in_sample: 8 },
  "222": { code: "222", column: "c_222", libelle: "Production stockée", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 8 },
  "7Z": { code: "7Z", column: "c_7z", libelle: "Autres emprunts obligataires brut à un an au plus", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 8 },
  "682": { code: "682", column: "c_682", libelle: "AUGMENTATIONS Total Relevé des provisions", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 8 },
  "088": { code: "088", column: "c_088", libelle: "Caisse", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 8 },
  "AL": { code: "AL", column: "c_al", libelle: "Avances et acomptes sur immobilisations incorporelles", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 8 },
  "154": { code: "154", column: "c_154", libelle: "Provisions pour risques et charges - Total II", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 7 },
  "Z1": { code: "Z1", column: "c_z1", libelle: "Créances représentatives de titres prêtés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 7 },
  "484": { code: "484", column: "c_484", libelle: "DIMINUTIONS Immobilisations financières", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 7 },
  "DS": { code: "DS", column: "c_ds", libelle: "Emprunts obligataires convertibles", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 7 },
  "R1": { code: "R1", column: "c_r1", libelle: "Compte de résultat - Intérêts et produits assimilés", pages: [1,4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 6 },
  "P2": { code: "P2", column: "c_p2", libelle: "P2", pages: [1,2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 6 },
  "432": { code: "432", column: "c_432", libelle: "AUGMENTATIONS Imm. corporelles – Constructions", pages: [3], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 6 },
  "4J": { code: "4J", column: "c_4j", libelle: "Provisions pour perte sur marchés à terme", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 6 },
  "130": { code: "130", column: "c_130", libelle: "Réserves réglementées", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 6 },
  "124": { code: "124", column: "c_124", libelle: "Ecarts de réévaluation", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 5 },
  "5R": { code: "5R", column: "c_5r", libelle: "Provisions pour charges sociales et fiscales sur congés à payer", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 5 },
  "P3": { code: "P3", column: "c_p3", libelle: "P3", pages: [1], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 4 },
  "684": { code: "684", column: "c_684", libelle: "DIMINUTIONS Total Relevé des provisions", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 4 },
  "P1": { code: "P1", column: "c_p1", libelle: "P1", pages: [1], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 4 },
  "P7": { code: "P7", column: "c_p7", libelle: "PASSIF - Report à nouveau", pages: [1,2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 4 },
  "DM": { code: "DM", column: "c_dm", libelle: "Produit des émissions de titres participatifs", pages: [2], colonnes: ["m3/m4"], occurrences_in_sample: 4 },
  "R3": { code: "R3", column: "c_r3", libelle: "Compte de résultat - Résultat de l’exercice", pages: [1], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 4 },
  "R5": { code: "R5", column: "c_r5", libelle: "Résultat net des entreprises intégrées", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 4 },
  "NC": { code: "NC", column: "c_nc", libelle: "DIMINUTIONS Virement postes - Avances et acomptes", pages: [5], colonnes: ["m3/m4"], occurrences_in_sample: 3 },
  "224": { code: "224", column: "c_224", libelle: "Production immobilisée", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 3 },
  "EF": { code: "EF", column: "c_ef", libelle: "Dont réserve réglementée des plus-values à long terme", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 3 },
  "316": { code: "316", column: "c_316", libelle: "Rémunération et avantages personnels non déductibles", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 3 },
  "402": { code: "402", column: "c_402", libelle: "AUGMENTATIONS Immobilisations incorporelles – Fonds commercial", pages: [3], colonnes: ["m1/m2"], occurrences_in_sample: 3 },
  "P8": { code: "P8", column: "c_p8", libelle: "PASSIF - Résultat de l’exercice", pages: [1], colonnes: ["m1/m2"], occurrences_in_sample: 3 },
  "P9": { code: "P9", column: "c_p9", libelle: "TOTAL PASSIF", pages: [1], colonnes: ["m1/m2"], occurrences_in_sample: 3 },
  "414": { code: "414", column: "c_414", libelle: "DIMINUTIONS Immobilisations incorporelles –Autres immobilisations incorporelles", pages: [3], colonnes: ["m1/m2"], occurrences_in_sample: 3 },
  "R2": { code: "R2", column: "c_r2", libelle: "Compte de résultat - Intérêts et charges assimilées", pages: [1], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 3 },
  "R6": { code: "R6", column: "c_r6", libelle: "Résultat Groupe (Résultat net consolidé)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 3 },
  "R8": { code: "R8", column: "c_r8", libelle: "Résultat net part du groupe (part de la société mère)", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 3 },
  "624": { code: "624", column: "c_624", libelle: "DIMINUTIONS Provisions pour risques et charges", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 3 },
  "197": { code: "197", column: "c_197", libelle: "Dont créances à plus d’un an", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 2 },
  "422": { code: "422", column: "c_422", libelle: "AUGMENTATIONS Imm. corporelles – Terrains", pages: [3], colonnes: ["m1/m2"], occurrences_in_sample: 2 },
  "7Y": { code: "7Y", column: "c_7y", libelle: "Emprunts obligataires convertibles brut à un an au plus", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 2 },
  "P6": { code: "P6", column: "c_p6", libelle: "Dans les résultats", pages: [1,2], colonnes: ["m1/m2"], occurrences_in_sample: 2 },
  "P5": { code: "P5", column: "c_p5", libelle: "PASSIF - Réserves", pages: [1], colonnes: ["m1/m2"], occurrences_in_sample: 2 },
  "652": { code: "652", column: "c_652", libelle: "AUGMENTATIONS Provisions pour dépréciation – Sur clients et comptes rattachés", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 2 },
  "AA": { code: "AA", column: "c_aa", libelle: "Capital souscrit non appelé", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 2 },
  "Z2": { code: "Z2", column: "c_z2", libelle: "Dette représentative de titres empruntés", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 2 },
  "UO": { code: "UO", column: "c_uo", libelle: "(provision pour dépréciation antérieurement constituée)", pages: [8], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 2 },
  "215": { code: "215", column: "c_215", libelle: "Production vendue de biens - Export", pages: [2], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 2 },
  "642": { code: "642", column: "c_642", libelle: "AUGMENTATIONS Provisions pour dépréciation – Sur stocks et en cours", pages: [4], colonnes: ["m1/m2","m3/m4"], occurrences_in_sample: 2 },
  "R4": { code: "R4", column: "c_r4", libelle: "R4", pages: [1], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "P4": { code: "P4", column: "c_p4", libelle: "PASSIF - Primes d’émission", pages: [1], colonnes: ["m1/m2"], occurrences_in_sample: 1 },
  "654": { code: "654", column: "c_654", libelle: "DIMINUTIONS Provisions pour dépréciation – Sur clients et comptes rattachés", pages: [4], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "662": { code: "662", column: "c_662", libelle: "AUGMENTATIONS Provisions pour dépréciation – Autres provisions pour dépréciation", pages: [4], colonnes: ["m1/m2"], occurrences_in_sample: 1 },
  "4N": { code: "4N", column: "c_4n", libelle: "Provisions pour amendes et pénalités", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "5B": { code: "5B", column: "c_5b", libelle: "Provisions pour impôts", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "602": { code: "602", column: "c_602", libelle: "AUGMENTATIONS Provisions réglementées – Amortissements dérogatoires", pages: [4], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "612": { code: "612", column: "c_612", libelle: "AUGMENTATIONS Provisions réglementées – Autres provisions réglementées", pages: [4], colonnes: ["m1/m2"], occurrences_in_sample: 1 },
  "622": { code: "622", column: "c_622", libelle: "AUGMENTATIONS Provisions pour risques et charges", pages: [4], colonnes: ["m1/m2"], occurrences_in_sample: 1 },
  "02": { code: "02", column: "c_02", libelle: "sur immobilisations – titres mis en équivalence", pages: [7], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "VX": { code: "VX", column: "c_vx", libelle: "Obligations cautionnées", pages: [8], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "632": { code: "632", column: "c_632", libelle: "AUGMENTATIONS Provisions pour dépréciation – Sur immobilisations", pages: [4], colonnes: ["m1/m2"], occurrences_in_sample: 1 },
  "YR": { code: "YR", column: "c_yr", libelle: "Engagement de crédit-bail immobilier", pages: [11], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "YS": { code: "YS", column: "c_ys", libelle: "Effets portés à l’escompte et non échus", pages: [11], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
  "644": { code: "644", column: "c_644", libelle: "DIMINUTIONS Provisions pour dépréciation – Sur stocks et en cours", pages: [4], colonnes: ["m1/m2"], occurrences_in_sample: 1 },
  "R7": { code: "R7", column: "c_r7", libelle: "Part des intérêts minoritaires (Résultat hors groupe)", pages: [4], colonnes: ["m3/m4"], occurrences_in_sample: 1 },
};

export const CERFA_COLUMNS = Object.values(CERFA_CODE_MAP).map(m => m.column);
